version: "3.8"

services:
  Postgres:
    container_name: postgres
    image: postgres:latest
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_PASSWORD=KOROTKOV_203
      - POSTGRES_USER=KOROTKOV_203
      - POSTGRES_DB=KOROTKOV_203
    volumes:
      - ./config/:/etc/postgresql/
      - ./scripts/:/docker-entrypoint-initdb.d/
      - ./data/:/var/lib/postgresql/data/