version: "3.8"

services:
  Postgres:
    container_name: postgres
    image: postgres:latest
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=lainex
    volumes:
      - C:\Users\aderl\Desktop\DB\hw4\config\:/etc/postgresql/
      - C:\Users\aderl\Desktop\DB\hw4\scripts\:/docker-entrypoint-initdb.d/